version: '3'  # Use the appropriate version

services:
  web:
    image: my-web-app:latest  # Use your web application image name
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - ./app:/app  # Mount the host directory into the container
    depends_on:
      - mongo  # Ensure the "mongo" service is running before starting "web"

  mongo:
    image: mongo:latest  # Use the MongoDB image
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    ports:
      - "27017:27017"  # Map host port 27017 to container port 27017
