# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  # dockerRegistryServiceConnection: '3919acec-e568-4d31-8c66-c887f9ffd353'
  dockerfilePath: "$(Build.SourcesDirectory)/Dockerfile"
  tag: "$(Build.BuildId)"
  imageTag: "build-tag-1"
  # Agent VM image name
  vmImageName: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: DockerBuildAndPush
        displayName: Docker Build and Push
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Build Docker image
            inputs:
              command: build
              repository: "tst18221162.azurecr.io/vibe-rec"
              containerRegistry: "TubesTSTDocker"
              dockerfile: $(dockerfilePath)
              tags: |
                $(imageTag)
              arguments: "--build-arg DATABASE_URL=$(DATABASE_URL) --build-arg KEY=$(KEY) --build-arg ALGORITHM=$(ALGORITHM) --build-arg SUPERADMIN_SECRET_KEY=$(SUPERADMIN_SECRET_KEY) --build-arg USERNAME=$(USERNAME) --build-arg PASSWORD=$(PASSWORD)"

          - task: Docker@2
            displayName: Push Docker image to registry
            inputs:
              command: push
              repository: "tst18221162.azurecr.io/vibe-rec"
              containerRegistry: "TubesTSTDocker" # Update with your container registry service connection name
              tags: |
                $(imageTag)
